name: Build
on:
  push:
    branches: [ master ]
    paths-ignore:
    - '.github/workflows/tag.yml'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    concurrency:
      group: ${{ github.sha }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Build
        uses: ./.github/actions/build
