name: Build
on:
  push:
   paths-ignore:
    - '.github/workflows/tag.yml'
  workflow_dispatch:

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
          echo "modules.lsposed.org" > ./public/CNAME
        env:
          GRAPHQL_TOKEN: ${{ secrets.GRAPHQL_TOKEN }}
      - uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
          git-config-name: "null"
          git-config-email: "null"
          single-commit: true
