name: Build
on:
  push:
   paths-ignore:
    - '.github/workflows/tag.yml'
  workflow_run:
    workflows: ["Tag"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: cache node modules
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-
      - name: cache gatsby cache
        uses: actions/cache@v2
        with:
          path: |
            .cache
          key: ${{ runner.os }}-gatsby-cache-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-gatsby-cache-
      - name: cache gatsby public
        uses: actions/cache@v2
        with:
          path: |
            public
          key: ${{ runner.os }}-gatsby-public-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-gatsby-public-
      - name: Install and Build 🔧 # This example project is built using npm and outputs the result to the 'build' folder. Replace with the commands required to build your project, or remove this step entirely if your site is pre-built.
        run: |
          npm install
          npm run build
          echo "modules.lsposed.org" > ./public/CNAME
        env:
          GRAPHQL_TOKEN: ${{ secrets.GRAPHQL_TOKEN }}
          GATSBY_EXPERIMENTAL_PAGE_BUILD_ON_DATA_CHANGES: true
      - uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
          git-config-name: "null"
          git-config-email: "null"
          single-commit: true
