name: Build
on:
  push:
    branches: [ master ]
    paths-ignore:
    - '.github/workflows/tag.yml'
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: ${{ github.sha }}
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: ./.github/actions/build
