name: Tag
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'repo name'
        required: true
      release:
        description: 'release id'
        required: true
      apk:
        description: 'apk url'
        required: true
        default: 'null'

jobs:
  update_tag:
    runs-on: ubuntu-latest
    steps:
      - run: |
          wget -O release.apk '${{ github.event.inputs.apk }}'
          AAPT=$(ls $ANDROID_SDK_ROOT/build-tools/**/aapt2 | tail -1)
          echo $AAPT
          VERCODE=$($AAPT dump badging release.apk | head -1 | sed -n "/^package:/ s/^.*versionCode='\([0-9]*\)'.*/\1/p")
          echo $VERCODE
