name: Tag
on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'repo name'
        required: true
      release:
        description: 'release id'
        required: true
      apk:
        description: 'apk url'
        required: true
        default: 'null'

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{ github.event.inputs.repo }}!"
          echo "- in ${{ github.event.inputs.release }}!"
